# Generated by Django 4.2 on 2024-02-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageuser2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.CharField(default='default_unit', max_length=10),
            preserve_default=False,
        ),
    ]
